### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by kristian-helgesen** [kristoffer-tungland/ElectricityPriceApi#4]
<Error>
<Message>An error has occurred.</Message>
<ExceptionMessage>404</ExceptionMessage>
<ExceptionType>ElectricityPriceApi.Exceptions.FailedToGetDayAheadPricesException</ExceptionType>
<StackTrace> at ElectricityPriceApi.HttpClients.EntsoeHttpClient.GetHourPrices(GetHourPricesArgs args) in D:\a\ElectricityPriceApi\ElectricityPriceApi\ElectricityPriceApi\HttpClients\EntsoeHttpClient.cs:line 44 at ElectricityPriceApi.Services.Prices.PriceService.GetAveragePrices(GetAveragePricesArgs args) in D:\a\ElectricityPriceApi\ElectricityPriceApi\ElectricityPriceApi\Services\Prices\PriceService.cs:line 64 at ElectricityPriceApi.Functions.PriceFunctions.RunAveragePrices(HttpRequest req, ILogger log) in D:\a\ElectricityPriceApi\ElectricityPriceApi\ElectricityPriceApi\Functions\PriceFunctions.cs:line 80</StackTrace>
</Error>

**Comment by kristoffer-tungland** [comment]
I'm not sure what's going on! Getting the same on all examples from entsoe as well. Maybe their api is down.. 
Going to do some research stay tuned!

**Comment by kristoffer-tungland** [comment]
Looks like they have change the api url. A fix is coming now

**Comment by kristoffer-tungland** [comment]
The service is up again
